modLoader="javafml" 
loaderVersion="[34,)"
license="GPL3"

[[mods]]
modId="catalogue"
version="1.0.0"
displayName="Catalogue"
authors="MrCrayfish"
logoFile="catalogue.png"
description="Updates Forge's mod list with a new and improved design"
itemIcon="minecraft:map"
credits="Hatsondogs for creating icons"

[[dependencies.catalogue]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.catalogue]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
